// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocpvoscjwjbvsffxkkhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcHZvc2Nqd2pidnNmZnhra2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTU0MDksImV4cCI6MjA2NjEzMTQwOX0.Kc7GGtUuQWyQAkXhmi-pnIlxRFBTTmenPvITmYYvIPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);